### ISSUE TITLE
The graph generated from the adjacency matrix doesn't match with the one in google doc

### ISSUE THREAD

**Issue by Jiangyue-Wang** [guoziqi1275/CSE583_final_project#1]
# From adjacency matrix:

<img width="977" alt="Screenshot 2024-10-28 at 21 26 22" src="https://github.com/user-attachments/assets/a8f2cf47-e659-4007-b5c2-9c5468a1275f">

Note: add 1 to the indices in this graph, to match the numbers drawn below.

# From google doc:

<img width="509" alt="Screenshot 2024-10-28 at 21 26 42" src="https://github.com/user-attachments/assets/36cd4b22-f3a1-4ccb-b59e-1a84d7953f5b">

Please double-check the adjacency matrix to make sure they match with each other. I think there may be some misentries in line 1 (index 0), and the relationship between clusters with number 10,12,19 and 13,14,17,18 (index 9,11,18 and 12,13,16,17). Additionally, as the matrix has transitivity, nodes within a cluster should be linked with each other. For example, number 17 (index 16) should be linked with number 13, 14, and 18, but only connected with 13 in the adjacency matrix.

**Comment by Jiangyue-Wang** [comment]
We can discuss this in class tmr; I just wanted to try out the issues on GitHub. 😆

**Comment by courtneykirsten** [comment]
I have redone the matrix as a 21x21. So the network numbers remained the same, but I added a 0-row and column. The 0-node has a connection to node 4 and node 6.

**Comment by Jiangyue-Wang** [comment]
Thanks! The nodes are easier to refer to now. I can see that node 0 is connected to node 4 and node 6 from the 0th row of the matrix. But from the plot output, node 3 is also connected to them.
<img width="868" alt="Screenshot 2024-10-30 at 21 26 31" src="https://github.com/user-attachments/assets/ea2c797c-ee92-4e16-ad63-7b96aabd5a86">

Besides, the edges in each cluster do not seem to be complete? For example, in the cluster of node 0,3,4,6, in the 6th row (row for node 6), it shows "1" for node 0 and node 6, but "0" for node 3 and node 4 (while it should be "1" for all nodes 0,3,4,6).  In the 6th column, it correctly shows"1" for all nodes. Currently, this matrix is not symmetric, while it should be symmetric for undirected graphs. Maybe I can develop a function to check symmetry in the adjacency matrix?

**Comment by Jiangyue-Wang** [comment]
I created a new branch for this issue, we can try to fix this problem there.

**Comment by courtneykirsten** [comment]
Ok I updated the file and pushed to the branch. Let me know if it is fixed. I still cant see any figures or on my machine, so can't tel if the graph updated correctly. Thanks!
